server {
    listen 80;
    server_name localhost;

    root /var/www/html/WEB/;
    index index.php index.html;

    # PHP処理
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # login
    #location = /login.php {
    #    root /var/www/html;
    #    include fastcgi_params;
    #    fastcgi_pass php:9000;
    #    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #}

    # Admin
    #location /Admin/ {
    #    root /var/www/html;
    #    index index.php index.html;
    #    try_files $uri $uri/ /Admin/index.php?$query_string;
    #}

    # classes
    location /classes/ {
        deny all;
    }

    # upload 
location /upload/ {
    alias /var/www/html/WEB/upload/;
    autoindex off;
}

    # 静的ファイル処理
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
